[package]
name = "ramify"
version = "0.1.0"
authors = ["adam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ramify"
path = "src/bin.rs"

[dependencies]
maplit = "1.0.2"
nom = "5"
comment = "0.1"